# Using the `set` flag in `$ Helm install` overrides values here, 
# e.g. `--set favorite_drink=slurm`
favorite_drink: coffee
# Convention: Keep tree values as shallow as possible
# Helm will coalesce the default and overridden keys, be careful when overriding
favorite:
  drink: coffee
  food: pizza
pizzaToppings:
- jalapeno
- pepperoni
- onions'
# This will override the dessert config in /charts/mysubchart/values.yaml
mysubchart:
  dessert: ice cream
# Globals
global:
  salad: caesar